### ISSUE TITLE
http://www.meetup.com/pghpython/ no longer?

### ISSUE THREAD

**Issue by jasonkhanlar** [pghpy/pghpy.github.com#8]
What happened to http://www.meetup.com/pghpython/ ?

**Comment by bruceadams** [comment]
Pittsburgh Python has merged into Pittsburgh Code and Supply http://www.codeandsupply.co/. The old PghPython Meetup group has been shutdown. Please find our Python meetings on http://www.meetup.com/Pittsburgh-Code-Supply/.
